locals {
  envs = {
    for tuple in regexall("(.*)=(.*)", file("../.env")) : tuple[0] => sensitive(replace(tuple[1], "\r", ""))
  }


  KNOWLEDGE_BASE_BUCKET_NAME                    = local.envs["KNOWLEDGE_BASE_BUCKET_NAME"]
  BEDROCK_KNOWLEDGE_BASE_NAME                   = local.envs["BEDROCK_KNOWLEDGE_BASE_NAME"]
  BEDROCK_KNOWLEDGE_BASE_EMBEDDING_MODEL_ARN    = local.envs["BEDROCK_KNOWLEDGE_BASE_EMBEDDING_MODEL_ARN"]
  BEDROCK_KNOWLEDGE_BASE_EMBEDDING_MODEL_REGION = local.envs["BEDROCK_KNOWLEDGE_BASE_EMBEDDING_MODEL_REGION"]
  PYTHON_VERSION                                = local.envs["PYTHON_VERSION"]

  S3_BUCKET_PREFIX           = local.envs["S3_BUCKET_PREFIX"]
  LAYERS_OUTPUT_FOLDER_NAME  = local.envs["LAYERS_OUTPUT_FOLDER_NAME"]
  LAMBDAS_OUTPUT_FOLDER_NAME = local.envs["LAMBDAS_OUTPUT_FOLDER_NAME"]

  SPLIT_N_CONVERT_PDF_FN_NAME                        = local.envs["SPLIT_N_CONVERT_PDF_FN_NAME"]
  SPLIT_N_CONVERT_PDF_LAMBDA_FOLDER_PATH             = local.envs["SPLIT_N_CONVERT_PDF_LAMBDA_FOLDER_PATH"]
  SPLIT_N_CONVERT_PDF_LAMBDA_LAYER_NAME              = local.envs["SPLIT_N_CONVERT_PDF_LAMBDA_LAYER_NAME"]
  SPLIT_N_CONVERT_PDF_LAMBDA_LAYER_REQUIREMENTS_PATH = local.envs["SPLIT_N_CONVERT_PDF_LAMBDA_LAYER_REQUIREMENTS_PATH"]

  PAGE_OCR_FN_NAME                        = local.envs["PAGE_OCR_FN_NAME"]
  PAGE_OCR_LAMBDA_FOLDER_PATH             = local.envs["PAGE_OCR_LAMBDA_FOLDER_PATH"]
  PAGE_OCR_LAMBDA_LAYER_NAME              = local.envs["PAGE_OCR_LAMBDA_LAYER_NAME"]
  PAGE_OCR_LAMBDA_LAYER_REQUIREMENTS_PATH = local.envs["PAGE_OCR_LAMBDA_LAYER_REQUIREMENTS_PATH"]
}
